import 'package:flutter_test/flutter_test.dart';
import 'package:kinrel_avatar_studio/models/avatar_layer.dart';
import 'package:kinrel_avatar_studio/registry/asset_manifest.dart';
import 'package:kinrel_avatar_studio/registry/base_bodies.dart';

/// Integration tests for the V1 placeholder hair / glasses / accessory
/// assets generated by `scripts/generate_placeholder_layers.py`.
///
/// These tests run against the bundled `AssetManifest.json` produced by
/// `flutter pub get` + `flutter test`, so they verify the assets are
/// actually declared in `pubspec.yaml` and discoverable at runtime —
/// not just that the PNG files exist on disk.
void main() {
  late AssetManifest manifest;

  setUp(() async {
    manifest = await AssetManifest.load();
  });

  group('Hair library (placeholder PNGs)', () {
    test('male hair folder has at least 8 options', () async {
      final ids = manifest.listIds(AvatarLayer.hair, gender: Gender.male);
      expect(
        ids.length,
        greaterThanOrEqualTo(8),
        reason: 'spec requires 8-10 male hairstyles',
      );
    });

    test('female hair folder has at least 8 options', () async {
      final ids = manifest.listIds(AvatarLayer.hair, gender: Gender.female);
      expect(
        ids.length,
        greaterThanOrEqualTo(8),
        reason: 'spec requires 8-10 female hairstyles',
      );
    });

    test('every male hair ID resolves to a bundled PNG path', () {
      final ids = manifest.listIds(AvatarLayer.hair, gender: Gender.male);
      for (final id in ids) {
        final path = manifest.resolveLayerPath(
          AvatarLayer.hair,
          id: id,
          gender: Gender.male,
        );
        expect(path, isNotNull, reason: 'male hair "$id" has no PNG');
        expect(path!.startsWith('assets/avatars/hair/male/'), isTrue);
      }
    });

    test('every female hair ID resolves to a bundled PNG path', () {
      final ids = manifest.listIds(AvatarLayer.hair, gender: Gender.female);
      for (final id in ids) {
        final path = manifest.resolveLayerPath(
          AvatarLayer.hair,
          id: id,
          gender: Gender.female,
        );
        expect(path, isNotNull, reason: 'female hair "$id" has no PNG');
        expect(path!.startsWith('assets/avatars/hair/female/'), isTrue);
      }
    });

    test('known placeholder hair IDs are present (sanity check)', () {
      final maleIds = manifest
          .listIds(AvatarLayer.hair, gender: Gender.male)
          .toSet();
      final femaleIds = manifest
          .listIds(AvatarLayer.hair, gender: Gender.female)
          .toSet();

      // A subset of IDs we know were generated. If any of these are
      // missing, the generator script was edited without updating
      // expectations — investigate before changing this test.
      expect(
        maleIds,
        containsAll(<String>[
          'short_cropped',
          'short_side_part',
          'buzz_cut',
          'man_bun',
          'clean_shaven',
        ]),
      );
      expect(
        femaleIds,
        containsAll(<String>[
          'long_straight',
          'shoulder_bob',
          'ponytail',
          'hair_bun',
          'pixie_cut',
        ]),
      );
    });
  });

  group('Glasses library (placeholder PNGs)', () {
    test('glasses folder has at least 3 options', () {
      final ids = manifest.listIds(AvatarLayer.glasses);
      expect(
        ids.length,
        greaterThanOrEqualTo(3),
        reason: 'spec requires 3-4 glasses styles',
      );
    });

    test('known placeholder glasses IDs are present', () {
      final ids = manifest.listIds(AvatarLayer.glasses).toSet();
      expect(
        ids,
        containsAll(<String>['round_black', 'square_black', 'aviator_gold']),
      );
    });

    test('every glasses ID resolves to a bundled PNG path', () {
      final ids = manifest.listIds(AvatarLayer.glasses);
      for (final id in ids) {
        final path = manifest.resolveLayerPath(AvatarLayer.glasses, id: id);
        expect(path, isNotNull, reason: 'glasses "$id" has no PNG');
        expect(path!.startsWith('assets/avatars/glasses/'), isTrue);
      }
    });
  });

  group('Accessories library (placeholder PNGs)', () {
    test('accessories folder has at least 2 options', () {
      final ids = manifest.listIds(AvatarLayer.accessories);
      expect(
        ids.length,
        greaterThanOrEqualTo(2),
        reason: 'spec requires at least a watch + a necklace',
      );
    });

    test('known placeholder accessory IDs are present', () {
      final ids = manifest.listIds(AvatarLayer.accessories).toSet();
      expect(ids, containsAll(<String>['wrist_watch', 'pendant_necklace']));
    });

    test('every accessory ID resolves to a bundled PNG path', () {
      final ids = manifest.listIds(AvatarLayer.accessories);
      for (final id in ids) {
        final path = manifest.resolveLayerPath(AvatarLayer.accessories, id: id);
        expect(path, isNotNull, reason: 'accessory "$id" has no PNG');
        expect(path!.startsWith('assets/avatars/accessories/'), isTrue);
      }
    });
  });

  group('Base body thumbnails (integration with previous iteration)', () {
    test('all 12 base bodies have a body.png bundled', () {
      for (final b in kBaseBodies) {
        final path = manifest.baseBodyPath(b.id);
        expect(path, isNotNull, reason: '${b.id} is missing body.png');
        expect(path, 'assets/avatars/base/${b.id}/body.png');
      }
    });
  });
}
